// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDSVAQtOBjCDz9PRFSp2WNWL1vPPGMhyE',
    appId: '1:811733201627:web:48e47e1ec09ef98fe212fe',
    messagingSenderId: '811733201627',
    projectId: 'training-app-12f6c',
    authDomain: 'training-app-12f6c.firebaseapp.com',
    storageBucket: 'training-app-12f6c.appspot.com',
    measurementId: 'G-DTXRVD1WNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe8xmxodKu2Ed9V0RhLf-PJks-ArYX3pA',
    appId: '1:811733201627:android:64a66c7fba4c62fbe212fe',
    messagingSenderId: '811733201627',
    projectId: 'training-app-12f6c',
    storageBucket: 'training-app-12f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhajtWnag2TiSsYmq9XEbguOOTOAsU48I',
    appId: '1:811733201627:ios:9f9c8832f8fa2e03e212fe',
    messagingSenderId: '811733201627',
    projectId: 'training-app-12f6c',
    storageBucket: 'training-app-12f6c.appspot.com',
    iosClientId: '811733201627-7373634c3ang4f16tghp5gm38l9f9dnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhajtWnag2TiSsYmq9XEbguOOTOAsU48I',
    appId: '1:811733201627:ios:b3f6affbe1363108e212fe',
    messagingSenderId: '811733201627',
    projectId: 'training-app-12f6c',
    storageBucket: 'training-app-12f6c.appspot.com',
    iosClientId: '811733201627-4io8ciilng64ap1rrfcrd6prkns89tdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp.RunnerTests',
  );
}
